webrtc-rs/webrtc

- .github/workflows/webrtc.yml
- rtcp/src/raw_packet.rs
- transport/src/buffer.rs
I've fixed clippy errors and added a CI job for `cargo fmt` and `cargo clippy`!
> Fix clippy errors

- srtp/Cargo.toml
- srtp/src/cipher/cipher_aead_aes_gcm.rs
- srtp/src/cipher/cipher_aes_cm_hmac_sha1.rs
- srtp/src/cipher/mod.rs
- srtp/src/cipher/test.rs
- srtp/src/context.rs
- srtp/src/context/context_test.rs
- srtp/src/context/srtcp.rs
- srtp/src/context/srtcp_test.rs
- srtp/src/context/srtp.rs
- srtp/src/context/srtp_test.rs
- srtp/src/key_derivation/key_derivation_test.rs
- srtp/src/key_derivation/mod.rs
- srtp/src/option.rs
- srtp/src/protection_profile.rs
- srtp/src/protection_profile/protection_profile_test.rs
- srtp/src/session.rs
- srtp/src/session/session_rtcp_test.rs
- srtp/src/session/session_rtp_test.rs
Add Aead Aes Gcm support to SRTP. closes #2 @rainliu  @Sean-Der
> [SRTP] Cipher aead aes gcm

- dtls/Cargo.toml
- dtls/src/application_data.rs
- dtls/src/config.rs
- dtls/src/conn.rs
- dtls/src/crypto.rs
- dtls/src/errors.rs
- dtls/src/flight.rs
- dtls/src/flight/flight0.rs
- dtls/src/flight/flight1.rs
- dtls/src/flight/flight2.rs
- dtls/src/flight/flight3.rs
- dtls/src/flight/flight4.rs
- dtls/src/flight/flight5.rs
- dtls/src/flight/flight6.rs
- dtls/src/fragment_buffer.rs
- dtls/src/fragment_buffer/fragment_buffer_test.rs
- dtls/src/handshake/handshake_cache.rs
- dtls/src/handshaker.rs
- dtls/src/state.rs
still work in progress to make conn work
> merge conn branch to master

- dtls/src/cipher_suite.rs
- dtls/src/cipher_suite/cipher_suite_aes_128_gcm_sha256.rs
- dtls/src/cipher_suite/cipher_suite_aes_256_cbc_sha.rs
- dtls/src/conn/conn_test.rs
> [DTLS] Add RSA-related cipher suites

- README.md
> Add sponsorship section

- README.md
@rainliu quick update to the sponsorship URL :) Keep up the good work!
> Update to Stream sponsorship URL

- examples/reflect/reflect.rs
> feat: Add audio track to examples/reflect.

- src/peer_connection/operation/mod.rs
There was an underflow in the operations length when adding an operation
back on the queue. This happened because the length wasn't incremented,
but the operation was sent on the channel.
> Fix underflow in operations length

- Cargo.toml
- src/api/setting_engine/mod.rs
- src/api/setting_engine/setting_engine_test.rs
- src/ice_transport/ice_gatherer.rs
Sibling PR https://github.com/webrtc-rs/ice/pull/16
> Integrate UDP mux support for ICE

- src/rtp_transceiver/rtp_receiver/mod.rs
A couple of simple changes to reduce lock-time on a shared channel, and reduce lock-time accessing shared tracks field. 
#151
> Fixes #151

- src/peer_connection/sdp/session_description.rs
This is a proposed solution to #155
> Add offer/answer/pranswer constructors for RTCSessionDescription

- src/peer_connection/mod.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_receiver/mod.rs
- src/rtp_transceiver/rtp_sender/mod.rs
Don't know the proper procedure for PRing this repo, so please excuse me if I'm supposed to contribute to one of the crate repos instead.
I wanted to be able to print some of these objects and filled in some `Display` and `Debug` traits.
> Adding some debug and display traits

- src/peer_connection/mod.rs
- src/peer_connection/operation/mod.rs
- src/peer_connection/operation/operation_test.rs
Make it slightly easier to debug stuff to do with `Operation` by giving them descriptions
> Improve operations debuggability

- src/dtls_transport/mod.rs
even if certificate verification is disabled via settings. It's in line
with Pion
https://github.com/pion/webrtc/blob/7feac502862a6a8804179dbadb816654138f34e0/dtlstransport.go#L367-L373.
Replaced https://github.com/webrtc-rs/webrtc/pull/221
> dtls_transport: always set remote certificate

- interceptor/src/stats/interceptor.rs
- interceptor/src/stats/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/stats/mod.rs
I had to refactor the stats collection to split inbound and outbound
stats from one-another.
> Implement Remote Inbound Stats

- mdns/src/conn/mod.rs
Closes https://github.com/webrtc-rs/mdns/issues/23
Port of https://github.com/webrtc-rs/mdns/pull/25
> mdns: get_interface_addr_for_ip once per query

- interceptor/CHANGELOG.md
- interceptor/src/stats/interceptor.rs
- interceptor/src/stats/mod.rs
- rtcp/src/reception_report.rs
- webrtc/CHANGELOG.md
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/stats/mod.rs
Also refactors stats fairly significantly in preparation for this.
> Implement remote outbound stats

- ice/CHANGELOG.md
- ice/src/agent/agent_config.rs
- ice/src/agent/agent_gather.rs
- ice/src/agent/agent_gather_test.rs
- ice/src/agent/mod.rs
- ice/src/util/mod.rs
- ice/src/util/util_test.rs
- webrtc/CHANGELOG.md
- webrtc/src/api/setting_engine/mod.rs
- webrtc/src/ice_transport/ice_gatherer.rs
Changes ported from https://github.com/pion/webrtc/pull/2316
> Add IP filter to WebRTC SettingEngine and ICE AgentConfig

- ice/CHANGELOG.md
- ice/src/util/mod.rs
The logic was wrong and would actually remove many IPs.
> Fix IP filter

- README.md
Hi there! Glad to be a sponsor. I've updated the image to be a better quality one, and updated the URL. Thanks!
> Update sponsor image/URL in README.md

- examples/examples/broadcast/broadcast.rs
- examples/examples/reflect/reflect.rs
- examples/examples/save-to-disk-h264/save-to-disk-h264.rs
- examples/examples/save-to-disk-vpx/save-to-disk-vpx.rs
- examples/examples/swap-tracks/swap-tracks.rs
- webrtc/CHANGELOG.md
- webrtc/src/api/media_engine/media_engine_test.rs
- webrtc/src/api/media_engine/mod.rs
- webrtc/src/api/setting_engine/setting_engine_test.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/rtp_receiver_test.rs
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
- webrtc/src/track/track_local/track_local_static_test.rs
- webrtc/src/track/track_remote/mod.rs
This PR removes unnecessary async.
> Async refactor

- rtcp/src/source_description/mod.rs
- sctp/src/association/mod.rs
@yngrtc 3 hours ago you've made the same changes directly to the master branch as my first commit 3 days ago in #435  including the same mistakes @gmorenz addressed in his review of the PR.
I've cherry-picked my fix for the formatting issues into this PR.
> Fix comment indentation

- webrtc/Cargo.toml
- webrtc/src/lib.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/stats/mod.rs
- webrtc/src/track/track_remote/mod.rs
> Switched mid and rid to SmolStr

- sctp/src/association/association_internal.rs
- sctp/src/chunk/chunk_init.rs
I found that ForwardTsnSupp in sctp Init chunk is not supported in the latest branch.
> Sctp forward tsn issue

- util/src/sync/mod.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/peer_connection_test.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
This PR solved this issue https://github.com/webrtc-rs/webrtc/issues/422 .
This fix repeats behavior in other places like: https://github.com/webrtc-rs/webrtc/blob/5859550cac046376bd4c7a252e79199c54f44bb8/webrtc/src/rtp_transceiver/mod.rs#L399  and https://github.com/webrtc-rs/webrtc/blob/5859550cac046376bd4c7a252e79199c54f44bb8/webrtc/src/rtp_transceiver/mod.rs#L446
In this case, the call goes not to `MutexGuard` but to `Arc`.
> Stop pc bug

- webrtc/Cargo.toml
- webrtc/src/lib.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/stats/mod.rs
- webrtc/src/track/track_remote/mod.rs
https://lib.rs/crates/smol_str has implementations of serde `Serialize` and `Deserialize` behind a feature flag.
> Use native serde impl for SmolStr

- rtp/src/header.rs
in #472 I missed the cases when the extension is removed or replaced
> Fix packet padding when changing extension

- sdp/src/description/description_test.rs
- sdp/src/description/session.rs
Support RFC 3890 (TIAS) for unmarshaling bandwidth.
> Support RFC 3890

- dtls/Cargo.toml
x25519-dalek has stabilized at 2 :tada:
> Bump x25519-dalek to stable 2

- ice/src/agent/agent_gather.rs
Previous code assumed "there's actually only one", which isn't true, and the result was choosing a random address every time. Including all local addresses seems like more reasonable behaviour?
> Use all local IP addresses as candidates for mux too

- Cargo.lock
- dtls/examples/hub/Cargo.toml
- dtls/examples/hub/src/utilities.rs
Upgrade rustls-pemfile to 2.1.2 dependency
> Upgrade rustls-pemfile to 2.1.2 dependency

- sctp/src/association/mod.rs
Hello, I got a panic while listening inside a `tokio::select!`, the other future completed first which end up in a cancellation of the webrtc future, and `tokio::task::spawn_blocking` then return an error.
```
thread 'tokio-runtime-worker' panicked at .../webrtc-sctp-0.9.1/src/association/mod.rs:514:22:
called `Result::unwrap()` on an `Err` value: JoinError::Cancelled(Id(1742443))
```
This change remove the panick.
> fix panic on async task cancellation

- Cargo.lock
- dtls/Cargo.toml
This also removes syn 1.0 from the crate tree.
> Bump der-parser to 9.0

- srtp/src/cipher/cipher_aes_cm_hmac_sha1/ctrcipher.rs
- srtp/src/cipher/cipher_aes_cm_hmac_sha1/opensslcipher.rs
- srtp/src/context/context_test.rs
- srtp/src/context/mod.rs
- srtp/src/context/srtcp.rs
- srtp/src/context/srtcp_test.rs
- srtp/src/context/srtp.rs
- srtp/src/context/srtp_test.rs
- srtp/src/error.rs
I've ported roll over count fixes and packet length validation changes from PION.
This also includes tests :)
> Include fixes to SRTP

- stun/examples/stun_client.rs
I tried to run the cases under Windows, but some of them failed to run.
> fix: on windows platform , not recognition localhost ip address bugs,

- .gitattributes
- .pre-commit-config.yaml
- README.md
- devbox.json
- devbox.lock
To further improve contributor experience, this PR adds the following:
- devbox for a common development environment
- pre-commit hooks for formatting
> Add devbox and pre-commit hook

- rtp/src/codecs/h264/mod.rs
When using OBS in WHIP streaming mode, OBS will encode the H264 stream with AUD packets of size two. This causes the h264 depacketizer from webrtc-rc to fail with error `ErrShortPacket`.
As far as I can tell from the H264 specification, however, an AUD of size 2 is a valid unit:
```
- NAL Unit Header (1 byte):
- forbidden_zero_bit (1 bit)
- nal_ref_idc (2 bits)
- nal_unit_type (5 bits)
- AUD RBSP (Raw Byte Sequence Payload) (minimum 1 byte):
- primary_pic_type (3 bits)
- rbsp_trailing_bits()
- rbsp_alignment_zero_bits
```
This PR allows AUD NALU of size less than two, but retains existing behavior for all other NALU types.
> Fix handling of AUD NAL units with size 2

- stun/src/agent.rs
Reduce one layer of `if` statement.
> stun: simplify stop_with_error

- turn/src/client/binding.rs
direct use `Option` return value
> turn: client binding direct use `Option` value
