webrtc-rs/webrtc

- .github/workflows/webrtc.yml
closes https://github.com/webrtc-rs/webrtc/issues/5
reference: https://github.com/rust-lang/rustfmt/issues/3666
> Fix `cargo fmt` error

- .github/workflows/webrtc.yml
> Revert "Fix `cargo fmt` error"

- dtls/src/crypto/crypto_ccm.rs
- dtls/src/crypto/crypto_test.rs
> DTLS: crypto_ccm.rs implementation

- dtls/src/cipher_suite/cipher_suite_tls_ecdhe_ecdsa_with_aes_128_ccm.rs
- dtls/src/cipher_suite/cipher_suite_tls_ecdhe_ecdsa_with_aes_128_ccm8.rs
This is bug fix related to #28  .
`TLS_ECDHE_ECDSA_WITH_AES_128_CCM` and `TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8` should return `false` when thier `is_psk()` called.
> Fix wrong `is_psk` flag

- src/peer/peer_connection.rs
fix some issues in https://github.com/webrtc-rs/webrtc/issues/97.
> 2). why play-from-disk-renegotiation example can't add more grid
After the repair, `play-from-disk-renegotiation` can `addVideo` correctly.
> fix: Stop transceiver correctly.

- Cargo.toml
- src/peer_connection/mod.rs
- src/peer_connection/sdp/mod.rs
This fixes a bug where `set_local_description` would immediately trigger `on_negotiation_needed` even though a negotiation isn't needed. This happens because the [check](https://github.com/webrtc-rs/webrtc/blob/fc7e1ef9f9e7b5b6208abe808079bda23beb15c8/src/peer_connection/mod.rs#L471) for step 5.3.3 in `check_negotiation_needed` would always fail. 
`MediaDescription::attribute` did not allow distinguishing between an attribute that was missing and one that was present but had no value, such as `a=recvonly`.
This PR depends on this sibling PR in `webrtc-rs/sdp`: https://github.com/webrtc-rs/sdp/pull/9.
> Fix SDP attributes

- src/api/interceptor_registry/mod.rs
- src/api/media_engine/media_engine_test.rs
- src/api/media_engine/mod.rs
This changed when transitioning to 0.3, was wondering if we can revert to this not being async, it doesn't seem necessary, but I might be mistaken.
> Remove async from register_header_extension

- src/ice_transport/ice_candidate.rs
The names of the `RTCIceCandidateInit` fields when serializing/deserializing are changed to match the names in the WebRTC specification ([link](https://www.w3.org/TR/webrtc/#dom-rtcicecandidateinit)). Three of the fields are also made optional(/nullable) according to the specification.
Without these changes one gets exceptions when interacting with other WebRTC implementations (when serializing/deserializing the candidate data using the `RTCIceCandidateInit` struct).
I'm unsure about what values to use when creating the new `RTCIceCandidateInit` in the `to_json` function. The WebRTC specification only specifies that at least one of the `sdpMid` and `sdpMLineIndex` fields must be set.
Currently the values are set in the same way as the pion implementation (`usernameFragment` set to null): …
> Make RTCIceCandidateInit conform to WebRTC spec

- src/dtls_transport/mod.rs
It looks like we're not closing the connection upon
ErrNoSRTPProtectionProfile / ErrNoRemoteCertificate errors.
Plus we're logging the wrong error when fingerprint is bad.
> close DTLS conn upon err

- README.md
Replace outdated/missing example names in "To build all webrtc examples" section of README
> Fix example names in README

- src/api/media_engine/mod.rs
- src/data_channel/mod.rs
- src/dtls_transport/mod.rs
- src/ice_transport/ice_gatherer.rs
- src/ice_transport/mod.rs
- src/peer_connection/certificate.rs
- src/peer_connection/mod.rs
- src/peer_connection/peer_connection_internal.rs
- src/peer_connection/peer_connection_test.rs
- src/sctp_transport/mod.rs
- src/stats/mod.rs
- src/stats/stats_collector.rs
This is obviously not finished, but I was hoping to get some feedback on a few points.
* I don't see a way of getting `bytes_received` or `bytes_sent` out of things that implement `Conn`. I was hoping that I was just missing some connecting thing.
* Do you have any hints on getting `base64_certificate` and `issuer_certificate_id` from an `RTCCertificate`?
* Serialization and casting... I was thinking that it might make sense to keep things close to the raw types (enums, Instants, etc), and delay transformations up until someone serialized types to something else like JSON. Any thoughts?
* `StatsReport`... in golang, this is a map. I was assuming this would be a struct that could be serialized, but wanted to ask if there was a preference.
I've left the existing commented-out golang …
> Get stats from peer connection

- src/peer_connection/sdp/mod.rs
- src/peer_connection/sdp/sdp_test.rs
We were not including the connection line(`c=`) when rejecting track,
but the specification requires this. Firefox would reject SDPs without
this.
> Fix SDP for rejected tracks to conform to RFC

- src/api/media_engine/media_engine_test.rs
- src/api/media_engine/mod.rs
- src/error.rs
Fixes an issue where we would incorrectly map a given RTP extension ID to more than a single extension URI e.g. we'd map the id `3` to `urn:ietf:params:rtp-hdrext:sdes:mid` for an audio stream, but then map it `urn:3gpp:video-orientation` for a video stream negotiated later.
In this fix I've introduced a new field `propsed_header_extensions` which keeps track of the mappings from id to extension URI we have proposed but haven't yet negotiated completely. `header_extension` is no longer used to generate the `id` we assign a given extension.
In pseudo code here's what happens when we generate extensions.
```
if stream_type_negotiated(typ)
// Use negotiated mappings from negotiated_header_extensions as before
else
for local_extension in header_extensions
if not_relevant(local_extension, typ, …
```
> Fix RTP extension id collision

- src/api/media_engine/mod.rs
ref #193 
This adds AV1 mime/codec parameters needed for negotiation, and is enough to get RTP flowing
@k0nserv
> Add AV1 MimeType and RtpCodecParameters

- src/error.rs
- src/peer_connection/mod.rs
- src/peer_connection/peer_connection_internal.rs
- src/peer_connection/sdp/mod.rs
- src/peer_connection/sdp/sdp_test.rs
- src/peer_connection/signaling_state.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_receiver/mod.rs
- src/rtp_transceiver/rtp_receiver/rtp_receiver_test.rs
- src/rtp_transceiver/rtp_transceiver_test.rs
- src/track/track_remote/mod.rs
Instead of stopping transceivers when a media section transitions to
inactive we keep them active, then if they become active again we resume receiving.
> Handle inactive transceivers more correctly

- src/peer_connection/mod.rs
- src/peer_connection/peer_connection_internal.rs
- src/peer_connection/sdp/mod.rs
- src/peer_connection/sdp/sdp_test.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_receiver/mod.rs
- src/rtp_transceiver/rtp_transceiver_direction.rs
- src/rtp_transceiver/rtp_transceiver_test.rs
The previous change to transceiver direction behaviour(#201) was a step in the
right direction(lol) but it wasn't correct. In particular we were making
changes when applying a remote offer that should happen when applying a
remote or local answer. The state machine for receivers was also
incorrect.
Here's the full state machine for RTP Receivers
> Rework transceiver direction support further

- src/peer_connection/certificate.rs
- src/peer_connection/configuration.rs
Closes #168 
This PR adds `RTCCertificate::from_existing` method, which constructs `RTCCertificate` from an existing  DTLS certificate. An existing certificate might be needed in cases like [this](https://github.com/libp2p/rust-libp2p/pull/2622) where you need DTLS identity to be fixed for some period of time (whole duration of the certificate or some part of it).
> [peer_connection] allow persistent certificates

- src/error.rs
- src/peer_connection/mod.rs
- src/peer_connection/sdp/mod.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_sender/mod.rs
- src/rtp_transceiver/rtp_transceiver_direction.rs
The previous logic would put negotiation into an endless loop after
running `remove_track` due to incorrectly implementing the negotiation
check and handling of stream ids.
Upon calling `remove_track` the following steps were carried out:
1. Find the transceiver the sender passed to `remove_track` is associated with
2. Stop the sender and set its track to `None`.
There were three problems with this:
1. The `remove_track` implementation is mostly correct, but it didn't always update the transceivers direction.
2. When checking if negotiation is needed the logic wasn't quite correct.
3. When offering the offered msid attribute didn't comply with the specification, in particular the msid line(s) should stay the same regardless of changes to the track or the transceivers direction. 
In total …
> Correct msid handling for RtpSender

- src/stats/mod.rs
Previously the only way to access the values was serialising them and
then relying on stringly typed access.
> Make stats types pub so they can be used directly

- Cargo.toml
- src/sctp_transport/mod.rs
Allows for acceptance of already created data channels. Duplicates logic
already existing in pion at
https://github.com/pion/webrtc/blob/master/sctptransport.go#L162.
Refs https://github.com/webrtc-rs/data/pull/14
Replaces https://github.com/webrtc-rs/webrtc/pull/219
Co-authored-by: stuqdog <ethanrodkin@protonmail.com>
> update call to DataChannel::accept as per data pr #14

- src/data_channel/data_channel_state.rs
- src/dtls_transport/dtls_role.rs
- src/dtls_transport/dtls_transport_state.rs
- src/ice_transport/ice_candidate.rs
- src/ice_transport/ice_candidate_pair.rs
- src/ice_transport/ice_candidate_type.rs
- src/ice_transport/ice_connection_state.rs
- src/ice_transport/ice_credential_type.rs
- src/ice_transport/ice_gatherer_state.rs
- src/ice_transport/ice_gathering_state.rs
- src/ice_transport/ice_parameters.rs
- src/ice_transport/ice_protocol.rs
- src/ice_transport/ice_role.rs
- src/ice_transport/ice_transport_state.rs
- src/peer_connection/offer_answer_options.rs
- src/peer_connection/peer_connection_state.rs
- src/peer_connection/policy/bundle_policy.rs
- src/peer_connection/policy/ice_transport_policy.rs
- src/peer_connection/policy/rtcp_mux_policy.rs
- src/peer_connection/policy/sdp_semantics.rs
- src/peer_connection/sdp/sdp_type.rs
- src/peer_connection/signaling_state.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_codec.rs
- src/rtp_transceiver/rtp_receiver/mod.rs
- src/rtp_transceiver/rtp_sender/mod.rs
- src/rtp_transceiver/rtp_transceiver_direction.rs
- src/sctp_transport/sctp_transport_capabilities.rs
- src/sctp_transport/sctp_transport_state.rs
Rust 1.63.0 introduces new clippy lints that were failing CI, this fixes
them.
> Fix recent clippy lints

- src/api/mod.rs
- src/peer_connection/mod.rs
- src/peer_connection/peer_connection_internal.rs
- src/peer_connection/sdp/sdp_test.rs
- src/rtp_transceiver/mod.rs
- src/rtp_transceiver/rtp_sender/mod.rs
- src/track/track_local/mod.rs
Currently if `RTCRtpTransceiver::direction` is set to a valueq which
doesn't allow sending data, we happily keep sending data if the user
does `write_sample` or `write_rtp`.
This changes so that any writes are just dropped as long as the
direction doesn't permit sending.
> Pause RTP writing if direction indicates it

- Cargo.toml
- webrtc/Cargo.toml
This will fix the:
cargo build
**warning: profiles for the non root package will be ignored, specify profiles at the workspace root:**
package:   C:\git\xnorpx\webrtc\webrtc\Cargo.toml
workspace: C:\git\xnorpx\webrtc\Cargo.toml
> move profile to workspace

- data/Cargo.toml
- dtls/Cargo.toml
- ice/Cargo.toml
- interceptor/Cargo.toml
- mdns/Cargo.toml
- media/Cargo.toml
- rtcp/Cargo.toml
- rtp/Cargo.toml
- sctp/Cargo.toml
- srtp/Cargo.toml
- stun/Cargo.toml
- turn/Cargo.toml
- webrtc/Cargo.toml
Cargo allows specifying both a `path` and `version` for dependencies,
doing this makes publishing easier.
> It is possible to specify both a registry version and a git or path
> location. The git or path dependency will be used locally (in which
> case the version is checked against the local copy), and when
> published to a registry like crates.io, it will use the registry
> version. Other combinations are not allowed.
_From [The Cargo Book][0]_
[0]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
> Specify both path and version in crate deps

- interceptor/src/report/receiver/receiver_test.rs
A [previous fix][0] for this issue has proven not to work. With this we
make time entirely deterministic in this test, a practice that we should
use in other tests if successful here.
[0]: https://github.com/webrtc-rs/interceptor/commit/0a2e942e0591e45bfeba6eec7f18960f96e3c5ba
> Fix test_receiver_interceptor_jitter on Ubuntu

- webrtc/src/peer_connection/mod.rs
When applying an answer from the remote the value of
`current_direction`was correctly update, but the process to trigger any
side effect was incorrectly using `direction` instead of
`current_direction` to determine the previous direction.
> Fix current direction update when applying answer

- .github/workflows/cargo.yml
- .github/workflows/grcov.yml
With this change we'll cancel in-progress workflows when new code is
pushed.
> Add concurrency limit in CI

- interceptor/src/report/receiver/mod.rs
- interceptor/src/stats/interceptor.rs
- interceptor/src/stats/mod.rs
- rtcp/src/transport_feedbacks/transport_layer_nack/mod.rs
- rtcp/src/transport_feedbacks/transport_layer_nack/transport_layer_nack_test.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/peer_connection_test.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
- webrtc/src/stats/mod.rs
- webrtc/src/track/track_local/track_local_static_test.rs
This PR implements inbound and outbound RTP stats according to the 
[specification](https://www.w3.org/TR/webrtc-stats/), with some 
limitations.
> Add RTP Stats to stats report

- util/Cargo.toml
Build broke on 1.57.0 due to 2.3.0 being released
> Fix async-global-executor

- ice/Cargo.toml
- webrtc/Cargo.toml
some projects like https://github.com/bheisler/criterion.rs depend on regex: `1.3`. I don't see why 1.6 have to be a requirement.
> relax regex version requirement

- ice/CHANGELOG.md
- webrtc/src/ice_transport/ice_gatherer.rs
create_agent is called multiple times from multiple threads, however, it is not locked properly.
The code as written before:
1) Acquire lock
2) Check for early exit if agent is already in a usable state
3) Release lock
4) Build agent config
5) Acquire lock
6) Create agent and update value stored
7) Release lock
The issue is that two threads can get to step 4 at the same time, and hence the second one to complete step 6, obliterates the agent of the other.
Since building the agent config is cheap, it is cleaner to simply acquire the lock, and not release it until the function completes. So:
1) Acquire lock
2) Check for early exit if agent is already in a usable state
3) Build agent config
4) Create agent and update value stored
5) Release lock
---
An alternative is to do the early exit …
> Promote create_agent lock to top of function, to avoid race condition

- data/src/data_channel/mod.rs
- examples/examples/data-channels-flow-control/data-channels-flow-control.rs
- sctp/CHANGELOG.md
- sctp/src/stream/mod.rs
- webrtc/CHANGELOG.md
- webrtc/src/data_channel/mod.rs
With this minor changes, you can now provide `|| async {}` as OnBufferedAmountLowFn callback instead of 
`Box::new(|| Box::pin(async {}))`. Other callback APIs can be refactored like this one easily.
> Simplify OnBufferedAmountLowFn callback API

- examples/examples/data-channels-flow-control/data-channels-flow-control.rs
- ice/src/agent/agent_internal.rs
- ice/src/agent/agent_test.rs
- ice/src/agent/agent_vnet_test.rs
- ice/src/agent/mod.rs
- webrtc/src/data_channel/mod.rs
- webrtc/src/dtls_transport/mod.rs
- webrtc/src/error.rs
- webrtc/src/ice_transport/ice_gatherer.rs
- webrtc/src/ice_transport/mod.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/sctp_transport/mod.rs
- webrtc/src/track/track_remote/mod.rs
Almost all callbacks, whose name matches On*Fn pattern, reworked, except for those that were skipped with a comment why (check commits "Skip <callback_name>").
Callback representation reverted to `Box::new(|| async {})` because of `webrtc_ice::agent::agent_vnet_test::on_connected()` that returns boxed closure (we can't return non boxed closure).
> Rework almost all callbacks

- webrtc/CHANGELOG.md
- webrtc/src/api/media_engine/mod.rs
- webrtc/src/rtp_transceiver/rtp_transceiver_test.rs
We don't actually support handling RTX on a distinct SSRC and declaring
these causes Chrome(and maybe others) to not sent retransmissions within
the existing RTP stream. This all means that even if we emit NACKs the
resulting retransmissions will simply be ignored.
> Remove video/rtx codecs

- examples/examples/ice-restart/ice-restart.rs
To fix a 404 not found error when running the example.
> [ice-restart example]: directory for index.html uses examples/examples

- media/src/io/sample_builder/mod.rs
- media/src/io/sample_builder/sample_builder_test.rs
- media/src/io/sample_builder/sample_sequence_location.rs
- media/src/io/sample_builder/sample_sequence_location_test.rs
- media/src/lib.rs
libWebRTC, among others, will sometime send padding RTP packets to keep send rates steady. When they do the packets are sent after a complete sequence of RTP packets that form a Sample/GOP/Frame. Example:
* P0, Timestamp=1, Start
* P1, T=1
* P2, T=1, End(RTP Marker Bit set)
* P3, T=1, Padding
* P4, T=1, Padding
* P5, T=2, Start
* P6, T=2 End
Here, when building a sample using the packets P5 and P6 we'll have `prev_dropped_packets = 2`, however these dropped packets are inconsequential as they don't carry media. The stream of samples is unbroken, despite having dropped some packets. With the introduction of `prev_padding_packets` it's possible to distinguish between dropped packets that are likely to break the sample stream and these unimportant padding packets
> Handle empty RTP packets in Sample Builder

- examples/examples/data-channels-flow-control/README.md
- examples/examples/data-channels-flow-control/data-channels-flow-control.rs
All examples and tests should be reworked like this one to make it possible to rework inner callback representation.
Under "like this one" I mean reworking at least callbacks in examples and tests, so there is no logic outside of async blocks, only state management.
I want to merge this into master, and not into feature/rework-callbacks, because in this example old callback representation is used, it does not break anything and will not prevent the release in any way.
If I rework other examples, I will also use the old callback representation, since the examples are generally poorly written. It is too difficult to move them to a new representation at the moment, I will still have to rewrite them from scratch. So I don't want to rewrite and move them to a new representation at the same …
> Rework data-channels-flow-control example

- media/src/io/sample_builder/mod.rs
- media/src/io/sample_builder/sample_builder_test.rs
- media/src/io/sample_builder/sample_sequence_location.rs
Improve Sample Builder handling of padding packets
When sending video streams that are fairly static, such as a screen
share of an inactive screen, libWebRTC will insert padding RTP packets.
These were not correctly handled by sample builder, because of this
`SampleBuilder` would throw away packets carrying actual media.
There was also a bug where dropping packets because the sample head was
not at a partition start would double count the dropped packets(once in
`build_sample` and once in `purge_buffers`.
As an example libWebRTC will send streams like this:
```
p1(t=1, start=true)
p2(t=1)
p3(t=1)
p4(t=1, marker=true)
p5(t=1, padding=true)
p6(t=1, padding=true)
p7(t=1, padding=true)
p8(t=2, start=true, marker=true)
p9(t=2, padding=true)
p10(t=2, padding=true)
p11(t=2, padding=true)
``` …
> Improve Sample Builder padding handling for static streams

- webrtc/CHANGELOG.md
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/track/track_local/mod.rs
- webrtc/src/track/track_local/track_local_static_rtp.rs
- webrtc/src/track/track_local/track_local_static_sample.rs
When direction is such that we are not sending. The writing of RTP packets is stopped already in TrackBinding to avoid allocating sequence numbers when they are not needed.
> Pause in TrackBinding when direction is not send

- examples/examples/simulcast/simulcast.rs
- webrtc/CHANGELOG.md
- webrtc/src/api/interceptor_registry/mod.rs
- webrtc/src/api/media_engine/media_engine_test.rs
- webrtc/src/api/media_engine/mod.rs
- webrtc/src/error.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/rtp_transceiver_direction.rs
SDP has the syntax: `a=extmap:<id>/<direction> <uri>`
The /<direction> part is optional (and rarely seen it in the wild).
The current MediaEngine API makes it seem like it's possible to provide many directions for each map (it takes a Vec). This commit changes that sov only single optional direction can be provided.
This simplifies internal matching logic and fixes a bug where setting the transceiver direction `inactive`, would (incorrectly) result in no extmaps matching for the m-line.
> One single direction per extmap

- webrtc/CHANGELOG.md
- webrtc/src/api/media_engine/mod.rs
- webrtc/src/rtp_transceiver/rtp_codec.rs
Hi,
This just adds a mime type and resolves it to the G7xxPayloader. 
Telephone event packets are just a 4 byte payload, and I could add an even simpler payloader but I think the G7xxPayloader does the right thing here, even if the name is not really fitting this usecase.
Any other places this new codec would need mentioning?
> add support for the telephone-event codec

- README.md
The link still points to the archived repo. I've updated it to point to the same README in the monorepo
> Update README examples link following monorepo move

- data/CHANGELOG.md
- data/src/data_channel/mod.rs
- sctp/CHANGELOG.md
- sctp/src/stream/mod.rs
- stun/src/message.rs
- util/src/fixed_big_int/mod.rs
"Invocation of a shutdown implies an invocation of flush. Once this method returns Ready it implies that a flush successfully happened before the shutdown happened. That is, callers don’t need to call flush before calling shutdown. They can rely that by calling shutdown any pending buffered data will be written out."
https://docs.rs/tokio/1.21.2/tokio/io/trait.AsyncWrite.html#tymethod.poll_shutdown
> PollStream/PollDataChannel: flush before shutting down

- data/CHANGELOG.md
- data/src/data_channel/mod.rs
- sctp/CHANGELOG.md
- sctp/src/stream/mod.rs
- webrtc/CHANGELOG.md
Returning `Poll::Ready(Ok(n))` when `write_fut` is `Some` is incorrect since `buf` already contains new data and we should instead always return `Poll::Ready(Ok(buf.len()))` and update `write_fut`.
In the future, if/when we make `write` synchronous, this whole block could be simplified to just contain a single call (1 line) to `write`. See #344
> [PollStream/PollDataChannel] do not loose bytes

- sctp/CHANGELOG.md
- sctp/src/association/association_internal.rs
- sctp/src/queue/pending_queue.rs
- sctp/src/queue/queue_test.rs
- sctp/src/stream/mod.rs
which appends chunks to the back of the pending queue.
Consider the following two simultaneous calls to `send_payload_data`:
```
1. [beginning_fragment1, data2, data3, ending_fragment4]
2. [beginning_fragment5, data6, data7, ending_fragment8]
```
If `push` is used, due to individual locks, it's possible to end up with:
```
[beginning_fragment1, data2, beginning_fragment5, data3, data6, ending_fragment4,
data6, data7, ending_fragment8]
```
This will result in wrong data received by the remote.
> add `PendingQueue::append`

- data/src/data_channel/mod.rs
- sctp/CHANGELOG.md
- sctp/examples/ping.rs
- sctp/examples/pong.rs
- sctp/src/association/association_internal.rs
- sctp/src/association/association_internal/association_internal_test.rs
- sctp/src/association/association_test.rs
- sctp/src/queue/pending_queue.rs
- sctp/src/queue/queue_test.rs
- sctp/src/stream/mod.rs
- sctp/src/stream/stream_test.rs
There's no reason for it to be async because it just buffers the data in memory (actual IO is happening in a separate thread).
> [sctp] make `write` sync

- turn/CHANGELOG.md
- turn/src/allocation/mod.rs
On our servers, we found that after the TURN service runs for a long time, there will be a large number of UDP ports that are not released.
We found that the reason is that after the `packet_handler` task is started, if the client no longer uses the UDP connection, `relay_socket.recv_from` will never return. So we add a 10-second timeout here to check whether the allocation has been dropped every 10 seconds.
Fixes https://github.com/webrtc-rs/webrtc/issues/232
Refs https://github.com/webrtc-rs/turn/issues/13
> [TURN] Fix server relay UDP port not release problem.

- sdp/CHANGELOG.md
- sdp/src/description/session.rs
Nice to have implement traits to convert to and from string
let sdp_string = String::from(sdp);
let sdp = SessionDescription::TryFrom(sdp_string).unwrap();
> implement from and tryfrom string traits for SessionDescription

- examples/examples/broadcast/broadcast.rs
- examples/examples/reflect/reflect.rs
- examples/examples/rtp-forwarder/rtp-forwarder.rs
- examples/examples/save-to-disk-h264/save-to-disk-h264.rs
- examples/examples/save-to-disk-vpx/save-to-disk-vpx.rs
- examples/examples/simulcast/simulcast.rs
- examples/examples/swap-tracks/swap-tracks.rs
- webrtc/CHANGELOG.md
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/peer_connection_test.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/rtp_receiver_test.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
- webrtc/src/track/track_local/track_local_static_test.rs
Currently `RTCPeerConnection::on_track` accepts `OnTrackHdlrFn` which is:
```rust
pub type OnTrackHdlrFn = Box<
dyn (FnMut(
Option<Arc<TrackRemote>>,
Option<Arc<RTCRtpReceiver>>,
) -> Pin<Box<dyn Future<Output = ()> + Send + 'static>>)
+ Send
+ Sync,
>;
```
When according to the WebRTc spec `RTCTrackEvent` is supposed to be:
```webidl
interface RTCTrackEvent : Event {
readonly attribute RTCRtpReceiver receiver;
readonly attribute MediaStreamTrack track;
[SameObject] readonly attribute FrozenArray<MediaStream> streams;
readonly attribute RTCRtpTransceiver transceiver;
};
```
So, excluding `MediaStream`s, since i don't see it being used anywhere, this callback is supposed to look like this: 
```rust
pub type OnTrackHdlrFn = Box<
dyn (FnMut(
Arc<TrackRemote>,
Arc<RTCRtpReceiver>, …
```
> Make `RTCPeerConnection::on_track` spec-compliant

- mdns/CHANGELOG.md
- mdns/src/conn/mod.rs
Before this module would `info` log and every packet it received. It has been updated to match the `ice` module and use the trace level for incoming packets.
> Adjust logging levels in mDNS

- sctp/CHANGELOG.md
- sctp/examples/throughput.rs
- sctp/src/association/association_internal.rs
- sctp/src/association/mod.rs
- webrtc/CHANGELOG.md
As discussed in #360 the lock on the internal association is very contended in high send-bandwidth situations. This PR achieves two things:
1. Pull the marshalling of packets outside of the critical section thus reducing the time the lock is taken by the write loop
2. Schedule the marshalling and sending as a new tokio::task::Task which makes tokio schedule this on another thread allowing the read loop to make progress in parallel while the write loop is working on that
This in itself does not really increase the bandwidth but with improvements to the marshalling code itself gains can be head now, that were previously (at least partially) blocked by the lock contention.
It should also improve situations where both sides send a lot of data because then the write and read loops would both …
> [SCTP] Associtation lock contention

- sctp/CHANGELOG.md
- sctp/src/chunk/chunk_payload_data.rs
- sctp/src/packet.rs
- sctp/src/util.rs
- webrtc/CHANGELOG.md
As discussed in #360 the marshalling code has become a bottle neck in high bandwidth sending situations. I found two places that had a big effect on the performance, the hot path for this situation is marshalling packets with exactly one data chunk in them.
After this PR the marshalling is largely dominated by the CRC32 calculation which is... not easy to speed up.
> [SCTP] Optimize sctp packet marshalling

- sctp/CHANGELOG.md
- sctp/src/queue/payload_queue.rs
- webrtc/CHANGELOG.md
As discussed in #360 Gathering packets to send is a big chunk of the work the Association::write_loop is doing while in a critical section.
This PR improves the performance of this by making the payload queue more performant to push to.
Previously this did a full mergesort (O(n*log(n))) on all the in-flight TSNs, now it does a binary search (O(log(n)))
> [SCTP] improve payload queue push performance

- webrtc/CHANGELOG.md
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_transceiver_test.rs
The current implementation is:
```
pub struct RTCRtpTransceiver {
mid: Mutex<String>,                           //atomic.Value
sender: Mutex<Option<Arc<RTCRtpSender>>>,     //atomic.Value
receiver: Mutex<Option<Arc<RTCRtpReceiver>>>, //atomic.Value
...
}
```
Essentially, the empty string is used instead of `None` (`Option<String>`).
This PR makes the behavior of `mid` explicitly optional, and also replaces `Mutex` with `OnceCell`.
> Make RTCRtpTransceiver.mid spec-compliant

- sctp/src/packet.rs
- sctp/src/queue/pending_queue.rs
- sctp/src/util.rs
Refs https://github.com/webrtc-rs/webrtc/pull/364 and https://github.com/webrtc-rs/webrtc/pull/367
cc @KillingSpark
> sctp: remove unnecessary drops and use precise padding

- webrtc/CHANGELOG.md
- webrtc/src/dtls_transport/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/track/track_remote/mod.rs
The method by which we detected non-signaled SSRCs would silently drop a
few packets. This is particularly problematic for a video stream since
these initial packets usually contain the first part of a keyframe to
start the stream.
See: #386 
**Note:** The first packet read for each RTP stream is not processed by interceptors unfortunately.
> Prevent loss of initial packet(s) in RTP streams

- sctp/CHANGELOG.md
- sctp/src/queue/reassembly_queue.rs
Fixes an unwrapped add that only affects programs compiled in the dev profile ([release profile naturally wraps](https://doc.rust-lang.org/stable/book/ch03-02-data-types.html#integer-overflow)).
This issue should not affect applications built in release, but is surprising in dev nonetheless.  As this is my first contribution, I'm not too familiar with the codebase yet.  My primary fix is on line 270, while I only suspect line 318 also qualifies. I have not reproduced this issue for 318 and not certain how to test either issue directly -- any guidance here is appreciated.
Partial stacktrace of the panic:
```
thread 'async-compat/tokio-1' panicked at 'attempt to add with overflow', /home/cscorley/.cargo/registry/src/github.com-1ecc6299db9ec823/webrtc-sctp-0.7.0/src/queue/reassembly_queue.rs: …
```
> sctp: fix 'attempt to add with overflow' panic in dev profile

- sctp/src/association/association_internal.rs
Hi! We have been getting:
```
[2023-01-23T20:41:10Z WARN  webrtc_sctp::association::association_internal] [] failed validating packet init chunk expects a verification tag of 0 on the packet when out-of-the-blue
[2023-01-23T20:41:10Z WARN  webrtc::peer_connection::peer_connection_internal] failed to open data channel: there already exists a stream with identifier 
```
on the [test-plans](https://github.com/libp2p/test-plans/) CI for the ping interop tests between two node using the `WebRTC` transport which uses `webrtc-rs` underneath, [see here](https://github.com/libp2p/test-plans/actions/runs/3990270518/jobs/6843709448#step:11:9403) for a reproduction which then breaks the test as the node fails to open the data channel. 
While trying to debug the issue I found that when …
> sctp: set verification tag to zero on the INIT packet.

- ice/CHANGELOG.md
- ice/src/agent/mod.rs
- ice/src/mdns/mod.rs
- webrtc/src/ice_transport/ice_gatherer.rs
Seems to be used only for converting to `::QueryOnly`
> ice: Remove unused MulticastDnsMode:Unspecified variant.

- webrtc/src/api/mod.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/rtp_transceiver/mod.rs
This PR provides API for creating custom `RTCRtpSender`, `RTCRtpReceiver` and `RTCRtpTransceiver` and adding `RTCRtpTransceiver` to `RTCPeerConnection`.
> Custom `RTCRtpTransceiver` creating

- data/CHANGELOG.md
- data/Cargo.toml
- data/src/data_channel/mod.rs
- media/Cargo.toml
This is quite a heavy dependency and it is only in use in one place which IMO doesn't need it. A struct with all public fields an easily be built in a single expression using `Config { negotiated: true, ..Default::default() }`.
Here is the output of `cargo tree` for us. In this case, it is also the only place where we pull in `darling` which by itself is quite heavy:
> Remove `derive_builder` dependency

- media/src/io/h264_reader/mod.rs
This is useful for custom streams, that aren't blocking and implement a non-blocking IO model, where `io::ErrorKind::WouldBlock` is returned, along with other custom `io::Error` return values that are valid, but right now not exposed once the reader is wrapped within the `H264Reader`.
> Surfaces io::Error from H264Reader read.

- examples/examples/play-from-disk-h264/play-from-disk-h264.rs
- media/src/io/h264_reader/h264_reader_test.rs
- media/src/io/h264_reader/mod.rs
Chunk reading size should be left to consumer to configure based on source.
> Adds configurable capacity to H264Reader.

- webrtc/src/peer_connection/signaling_state.rs
This PR makes setting local `SDP` spec compliant (as described in **RFC8829** [section 5.5](https://datatracker.ietf.org/doc/html/rfc8829#section-5.5)).
> Allow setting local SDP for `RTCSignalingState::HaveLocalOffer`

- dtls/Cargo.toml
- curve25519-dalek is not used directly and is using old version causing dependency tree dups
- ~bump elliptic-curve to 0.13.5~ - this is not used so removed as redundant
- Remove redundant signature dependency
> Fix redundant / duplicate dependencies

- ice/src/agent/agent_vnet_test.rs
- ice/src/candidate/candidate_relay_test.rs
- ice/src/candidate/candidate_server_reflexive_test.rs
- turn/CHANGELOG.md
- turn/examples/turn_server_udp.rs
- turn/src/allocation/allocation_manager.rs
- turn/src/allocation/allocation_manager/allocation_manager_test.rs
- turn/src/allocation/allocation_test.rs
- turn/src/allocation/channel_bind/channel_bind_test.rs
- turn/src/allocation/mod.rs
- turn/src/auth/auth_test.rs
- turn/src/client/client_test.rs
- turn/src/server/config.rs
- turn/src/server/mod.rs
- turn/src/server/request/request_test.rs
- turn/src/server/server_test.rs
When using the turn service, we want to count the number of traffic bytes forwarded by each allocation in the application. I think a good time is when the allocation is closed. So I designed a parameter to pass an mpsc sender in, and send the AllocationInfo out to the application when the allocation is closed.
> Add alloc_close_notify config param.

- examples/examples/rtp-forwarder/rtp-forwarder.rs
- interceptor/src/lib.rs
- interceptor/src/mock/mock_stream.rs
- interceptor/src/nack/generator/generator_stream.rs
- interceptor/src/nack/responder/mod.rs
- interceptor/src/noop.rs
- interceptor/src/report/receiver/mod.rs
- interceptor/src/report/receiver/receiver_stream.rs
- interceptor/src/stats/interceptor.rs
- interceptor/src/stream_reader.rs
- interceptor/src/twcc/receiver/receiver_stream.rs
- media/src/io/sample_builder/mod.rs
- srtp/src/session/session_rtcp_test.rs
- srtp/src/session/session_rtp_test.rs
- srtp/src/stream.rs
- webrtc/CHANGELOG.md
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/srtp_writer_future.rs
- webrtc/src/track/track_remote/mod.rs
This PR optimizes multiple `unmarshal` in `Interceptor`.
closes  TODO: `interceptor/src/stats/interceptor.rs:732`
```
// TODO: This parsing happens redundantly in several interceptors, would be good if 
// could not do this.
```
> Unmarshal optimization

- media/src/io/ivf_writer/ivf_writer_test.rs
- media/src/io/ogg_writer/ogg_writer_test.rs
- media/src/io/sample_builder/mod.rs
- rtp/src/header.rs
- rtp/src/packetizer/packetizer_test.rs
I tried to retrieve media from mediasoup SFU. There is issue with calculation of RTP header size. I propose fix for this.
The stack does not count with padding data in header extensions field.
> Fix of rtp header size calculation

- media/src/io/sample_builder/mod.rs
- webrtc/src/peer_connection/mod.rs
Currently the stack cannot handle ICE-LITE peer and correctly initiate connection. This fix adjusts the correct DTLS role for ICE-LITE peer 
[Pion commit](https://github.com/pion/webrtc/commit/8796a5c5a7359e12f0164823631d6e25579a4260#diff-c94e5058864f96b58c5e039ac0485b3a9640613f32a9e31bba905dc3f8438e7a)
> Fix of dtls connection with lite ice role

- sctp/src/association/association_test.rs
- sctp/src/error.rs
- sctp/src/queue/queue_test.rs
- sctp/src/queue/reassembly_queue.rs
- sctp/src/stream/mod.rs
> [sctp] Include buffer size in `ErrShortBuffer`

- dtls/src/alert/mod.rs
- dtls/src/conn/mod.rs
As per RFC 4279 (Pre-Shared Key Ciphersuites for Transport Layer Security), Section 2:
>    If the server does not recognize the PSK identity, it MAY respond
with an "unknown_psk_identity" alert message.  Alternatively, if the
server wishes to hide the fact that the PSK identity was not known,
it MAY continue the protocol as if the PSK identity existed but the
key was incorrect: that is, respond with a "decrypt_error" alert.
> Returning an alert when PSK authentication fails.

- rtp/src/codecs/av1/av1_test.rs
- rtp/src/codecs/av1/leb128.rs
- rtp/src/codecs/av1/mod.rs
- rtp/src/codecs/av1/obu.rs
- rtp/src/codecs/av1/packetizer.rs
- rtp/src/codecs/mod.rs
- rtp/src/error.rs
- webrtc/src/api/media_engine/mod.rs
- webrtc/src/rtp_transceiver/rtp_codec.rs
Addresses https://github.com/webrtc-rs/webrtc/issues/193.
This PR implements the payloader for AV1, based on Chromium's implementation in C++: https://chromium.googlesource.com/external/webrtc/+/4e513346ec56c829b3a6010664998469fc237b35/modules/rtp_rtcp/source/rtp_packetizer_av1.cc, which supports packetizing payloads containing multiple OBUs.
Other references used are: 
- https://aomediacodec.github.io/av1-rtp-spec/#4-payload-format
- https://aomediacodec.github.io/av1-spec
- Relevant unit tests were ported over.
- Tested as being used in my own project (https://github.com/mira-screen-share/sharer/), which streams screen capture video encoded by FFMPEG `libsvtav1` and `libaom-av1` encoders. The video stream can be decoded by Chrome with no apparent issues.
1. In the current …
> Implement AV1 Payloader

- rtp/src/header.rs
after #454 i started getting
Error "marshal_to output size {n}, but expect {l}"
this was due to a change in packet header size calculation in #454
This PR fixes the behavior of `set_extension`.
> Fix `set_extension`

- util/src/ifaces/ffi/unix/mod.rs
- util/src/vnet/interface.rs
Hi!
In Linux, the last 8 octets from Ipv6 were being discarded when gathering local interfaces, making Ipv6 bindings fail.
This PR further simplifies Ip parsing.
(Relates to #473 )
> fix linux ipv6 handling

- examples/examples/data-channels/data-channels.rs
- interceptor/src/twcc/receiver/receiver_test.rs
- media/src/audio/buffer/info.rs
- rtcp/src/payload_feedbacks/receiver_estimated_maximum_bitrate/mod.rs
- rtp/src/codecs/vp8/mod.rs
- rtp/src/codecs/vp9/mod.rs
- sctp/src/association/association_internal.rs
- sctp/src/queue/queue_test.rs
- sctp/src/timer/timer_test.rs
- sdp/src/direction/direction_test.rs
- sdp/src/extmap/extmap_test.rs
- stun/src/integrity.rs
- stun/src/xoraddr.rs
- util/src/vnet/router/router_test.rs
- webrtc/src/data_channel/data_channel_test.rs
Resolves #468 
Currently the library does not properly implement the shutdown procedure for data channels closed by Chrome. In order for the data channel to fully close, it must receive a `OutgoingResetRequest`.
This was an existing issue in pion which has since been resolved here https://github.com/pion/sctp/pull/238
Using the [examples/data-channels](https://github.com/webrtc-rs/webrtc/tree/master/examples/examples/data-channels)
Run the JS test for closing data channels: [jsfiddle](https://jsfiddle.net/p4eov5xc/2/)
Note the RTCDataChannels never enter `closed` state.
> fix(data-channel): stuck closing in Chrome

- webrtc/src/peer_connection/mod.rs
When calling `add_track` and `remove_track` from `RTCPeerConnection` the msid is not updated on the SDP due to this requirement in the specification : https://datatracker.ietf.org/doc/html/rfc8829#section-5.2.2
Imagine the following scenario
```
let video_track = Arc::new(TrackLocalStaticSample::new(
RTCRtpCodecCapability {
mime_type: MIME_TYPE_H264.to_string(),
clock_rate: 90000,
..Default::default()
},
"MyStream1",
"MyStream1",
));
// Add this newly created track to the PeerConnection
let rtp_sender = self
.peer_connection
.add_track(Arc::clone(&video_track) as Arc<dyn TrackLocal + Send + Sync>)
.await
.unwrap();
```
We later then call `remove_track(video_track)` and then if you create a new video track with the id/label `NotMyStream1` the SDP still shows the old `MSID` with the value …
> Ensure track ID's match when re-using an RTCRtpTransceiver

- constraints/Cargo.toml
- constraints/src/algorithms/select_settings.rs
- constraints/src/errors.rs
The `SelectSettingsError` type was missing an impl for `std::error::Error`. While at it I migrated to using `thiserror`, like the rest of the workspace.
> Improve error types in `webrtc-constraints`, using `thiserror`

- turn/src/allocation/allocation_manager.rs
- turn/src/allocation/allocation_manager/allocation_manager_test.rs
- turn/src/error.rs
- turn/src/server/request.rs
- turn/src/server/request/request_test.rs
Fixes https://github.com/webrtc-rs/webrtc/issues/473
Includes `RequestedAddressFamily` attr in the `handle_X_request` functions as described in RFC 6156. 
Does not implement RFC 6156 Section 8 - Packet translations.
> turn: Implement RFC 6156

- media/src/io/ogg_writer/mod.rs
- media/src/io/ogg_writer/ogg_writer_test.rs
Implement the changes in https://github.com/pion/webrtc/pull/2531 which fixes https://github.com/pion/webrtc/issues/2472.
> **Description**
> PR adds packet segmentation capability to OggWriter. This makes it possible to accept payloads bigger than 255 bytes which are actually more common that I thought (e.g. Firefox seems to be generating quite a few). Without this change we'd be defaulting to a single segment causing data loss when writing and corrupted files as consequence.
> There's still a theoretical limit of 255 segments per page that we are not handling (packets spanning pages) but for encoded audio data I am hoping that shouldn't ever become an issue.
In addition to Firefox, OBS 30.0 Beta 3 frequently produces payloads larger than 255 bytes, even at the lowest bitrate setting of …
> feature(media/ogg_writer): add packet segments to page

- media/src/io/h264_reader/mod.rs
Fixes #505 
The following is benchmark with same code in #505
```
$ cargo run --example nal-parser -- ~/test.h264          
Finished dev [unoptimized + debuginfo] target(s) in 0.20s
Running `target/debug/examples/nal-parser /Users/anatawa12/test.h264`
Input file size: 6926816
Parsing NAL took: 486.273834ms
Total NALs: 1001
$ cargo run --release --example nal-parser -- ~/test.h264
Finished release [optimized] target(s) in 0.20s
Running `target/release/examples/nal-parser /Users/anatawa12/test.h264`
Input file size: 6926816
Parsing NAL took: 45.588834ms
Total NALs: 1001
```
> Faster H264Reader

- mdns/src/conn/mod.rs
This fixes the annoying warning when receiving a mdns packet with more than 3 questions
[2023-11-09T12:04:04Z WARN  webrtc_mdns::conn] Failed to parse mDNS packet parsing/packing of this type isn't available yet [2023-11-09T12:04:08Z WARN  webrtc_mdns::conn] Failed to parse mDNS packet parsing/packing of this type isn't available yet [2023-11-09T12:04:17Z WARN  webrtc_mdns::conn] Failed to parse mDNS packet parsing/packing of this type isn't available yet
> mdns: Skip rest of mdns questions when parsing packet

- sctp/src/association/mod.rs
Hi all,
I ran into some severe throughput issues with webrtc-rs, but I've managed to track down the problem. I was using webrtc through the [Matchbox](https://github.com/johanhelsing/matchbox) crate, and found my total throughput was limited to about **3 Mbps** across several different machines and networks.
The use of `tokio::task::spawn` when SCTP sends its packets to the underlying DTLS layer causes packets to send out of order. These out of order packets trigger SCTP's congestion control mechanisms, limiting total throughput to around 3 Mbps on machines I tested. Changing the code to guarantee packet ordering at the time of sending resolves the issue.
Here's the source of the problem:
https://github.com/webrtc-rs/webrtc/pull/363/files#diff-26a945150f33caddc941f57968f74224cba89af5a0ac4a …
> Fixed throughput issues by fixing lack of guarentee on SCTP -> DTLS packet ordering

- mdns/src/conn/mod.rs
Currently, the `INBOUND_BUFFER_SIZE` is 512 bytes, which means that the data gets truncated in the `recv_from` call in `start` when the incoming payload is larger (happens a lot in our office network, for example).
The problem is that this happens silently on Unix systems and everything works OK (well, the messages are truncated, but still). Unfortunately on Windows `socket.recv_from` actually returns an error in this case - `WSAEMSGSIZE (10040)` and mDNS starts logging errors and doesn't behave the same.
This is currently blocking us using using WebRTC via this crate on Windows.
For more info, see:
https://docs.rs/mio/latest/mio/net/struct.UdpSocket.html#method.recv_from as excerpted here:
The UDP buffer can be up to 64k so this PR bumps it to the maximum size to avoid this difference in …
> Fix mDNS INBOUND_BUFFER_SIZE. Fixes Windows misbehaving.

- sctp/src/association/association_test.rs
- webrtc/src/mux/mod.rs
- webrtc/src/mux/mux_test.rs
This PR implements [pion commit 2184](https://github.com/pion/webrtc/pull/2184). 
Currently it's assumed that the read buffer will never fill, and so any failure to `write` should be cause to return an `Err`. This isn't always true however, particularly in high load scenarios. Per `pion` fixes, we should instead log and drop packets when the buffer is full, and continue to return an error in other failure cases.
See https://github.com/pion/webrtc/issues/2152 and https://github.com/pion/webrtc/issues/2180 for more details.
> Implement pion commit 2184 - mux: drop packets when buffer is full

- util/src/ifaces/ffi/unix/mod.rs
By relying on nix to handle the kernel/libc call complexities, this removes all unsafe code blocks and just makes the code pretty readable and straight forward.
> ifaces: Use nix::ifaddrs::getifaddrs() 100%

- util/Cargo.toml
`webrtc-util` uses `IpNet::with_netmask`, which was introduced in version 2.6.0. If someone is using a `Cargo.lock` with an older version of `ipnet`, they'll get a compile error when introducing `webrtc-util` (or upgrading it to after this call was added). Adding the correct version requirement in `Cargo.toml` forces the upgrade to fix this.
> fix understated `ipnet` version requirement

- webrtc/src/lib.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
This improves parsing and generation of SDP for simulcast attribute according to RFC8853.
Support for alternative formats are not implemented 100%.
Comparing to Pion implementation, this commit at least covers more, hopefully most usecases for webrtc-rs users.
> sdp: simulcast: Properly parse and set 'a=simulcast:'

- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
This makes sure that rids are not reordered when doing offer <-> answer
> sdp: Use vector instead of HashMap for SimulcastRid

- dtls/src/crypto/crypto_cbc.rs
- dtls/src/crypto/mod.rs
- dtls/src/crypto/padding.rs
We found use OBS-studio WHIP cannot PeerConnected
package DTLS have problem
We found after this commit have this bug
This PR https://github.com/webrtc-rs/webrtc/pull/496 and this commit after https://github.com/webrtc-rs/webrtc/pull/496/commits/935283abc719b2c3a6925cd8bb90ffb3809bccc5
Finally we found the problem. But, I'm not sure this have bug 
https://github.com/RustCrypto/utils/blob/master/block-padding/src/lib.rs#L176-L216
Maybe, webrtc-rs is using this library incorrectly
https://github.com/binbat/live777/issues/39
https://github.com/binbat/live777/issues/58
> fix OBS-studio DTLS failed

- sdp/src/extmap/mod.rs
- webrtc/src/lib.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/rtp_receiver_test.rs
This is a patchset which at least improves using webrtc-rs on a SFU with simulcast and firefox as a client
I found that the simulcast example didn't work for Firefox. It might not really work now either, but this should be a step on the way.
Please let me know what you think :)
> Fix simulcast for firefox

- dtls/src/conn/mod.rs
- ice/src/agent/agent_test.rs
- ice/src/agent/agent_transport.rs
- ice/src/agent/agent_vnet_test.rs
- ice/src/udp_mux/udp_mux_conn.rs
- sctp/src/association/association_internal/association_internal_test.rs
- sctp/src/association/association_test.rs
- turn/src/client/relay_conn.rs
- util/src/conn/conn_bridge.rs
- util/src/conn/conn_disconnected_packet.rs
- util/src/conn/conn_pipe.rs
- util/src/conn/conn_udp.rs
- util/src/conn/conn_udp_listener.rs
- util/src/conn/mod.rs
- util/src/vnet/conn.rs
- webrtc/src/mux/endpoint.rs
- webrtc/src/mux/mux_test.rs
This allows you to access the inner connection state of the DTLS connection. Having the connection identity is helpful in server code.
> Add as_any to Conn trait for accessing underlying Conn

- Cargo.lock
- dtls/Cargo.toml
- dtls/examples/dial/verify/dial_verify.rs
- dtls/examples/hub/Cargo.toml
- dtls/examples/hub/src/utilities.rs
- dtls/examples/listen/verify/listen_verify.rs
- dtls/src/conn/conn_test.rs
- dtls/src/conn/mod.rs
- dtls/src/crypto/crypto_test.rs
- dtls/src/crypto/mod.rs
- dtls/src/error.rs
- dtls/src/flight/flight4.rs
- dtls/src/flight/flight5.rs
- dtls/src/handshaker.rs
- webrtc/Cargo.toml
- webrtc/src/api/mod.rs
- webrtc/src/error.rs
- webrtc/src/peer_connection/certificate.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
Update Depend:
- rcgen
- rustls
- x509-parser
* * *
Remove Depend `ring == 1.6`, Because. The `ring == 1.6` cannot compile in Windows on `aarch`
https://github.com/binbat/live777/issues/73
* * *
For `rustls == 0.23.5`, `WebPkiServerVerifier` don't support `rustls::RootCertStore::empty()`. The test need changed
https://docs.rs/rustls/0.23.5/src/rustls/webpki/server_verifier.rs.html#100-113
> Update depend rcgen

- sctp/CHANGELOG.md
- sctp/Cargo.toml
- sctp/src/util.rs
The crc crate has released finally released a new version featuring an improved algorithm that greatly increases performance. The new algorithm uses a few Kb more of lookup tables which is why it has to be enabled explicitly. This PR bumps the version of the crc crate to the required level and enables that new algorithm.
Crc performance is a significant bottleneck in the sctp throughput as showcased by the throughput example:
```
Throughput: 67238910 Bytes/s, 1026 pkts, 1026 loops
Send 1031 pkts
Throughput: 68025330 Bytes/s, 1038 pkts, 1038 loops
Send 1038 pkts
Throughput: 68484075 Bytes/s, 1045 pkts, 1045 loops
Send 1049 pkts
Throughput: 68353005 Bytes/s, 1043 pkts, 1043 loops
Send 1046 pkts
Throughput: 68746215 Bytes/s, 1049 pkts, 1049 loops
Send 1050 pkts
Throughput: 67632120 Bytes/s, …
```
> use the new feature of the crc crate for more throughput in sctp

- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
Implemented like in pion
https://github.com/pion/webrtc/pull/2564
> Match group bundle from offer

- rtp/src/error.rs
- rtp/src/extension/mod.rs
- rtp/src/extension/playout_delay_extension/mod.rs
- rtp/src/extension/playout_delay_extension/playout_delay_extension_test.rs
Adds a `PlayoutDelayExtension` per https://webrtc.googlesource.com/src/+/main/docs/native-code/rtp-hdrext/playout-delay/README.md, using https://github.com/pion/rtp/blob/master/playoutdelayextension.go for reference.
> Added PlayoutDelayExtension to control receiver jitter buffer size

- constraints/Cargo.toml
- data/Cargo.toml
- dtls/Cargo.toml
- examples/Cargo.toml
- ice/Cargo.toml
- interceptor/Cargo.toml
- mdns/Cargo.toml
- media/Cargo.toml
- rtcp/Cargo.toml
- rtp/Cargo.toml
- sctp/Cargo.toml
- sdp/Cargo.toml
- srtp/Cargo.toml
- stun/Cargo.toml
- turn/Cargo.toml
- util/Cargo.toml
Discovering all the sub-crates from docs.rs is sub-optimal, as the links to crates of the workspace are not all working.
Example: from https://docs.rs/webrtc-srtp/latest/webrtc_srtp/, the "Repository" link links to the archived, pre-workspace version of the crate.
This MR fixes them.
> Fixed repository URLs

- webrtc/src/peer_connection/mod.rs
I had fixed this previously, but it seems that the sender.id() is not the same as the track.id()
> - Fix add_track to re-use existing transceivers with the same track_id

- webrtc/src/api/mod.rs
- webrtc/src/error.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/peer_connection_test.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
- webrtc/src/track/track_local/mod.rs
- webrtc/src/track/track_local/track_local_static_rtp.rs
- webrtc/src/track/track_local/track_local_static_sample.rs
Most of this is ported from different patches in pion related to send side simulcast.
First and foremost, a track can now be created with a specific RID, and `RtpSender::add_encoding()` is used for adding track encodings. Also, MID and RID RTP header extensions are automatically added when sending RTP/Samples on local tracks. All of this would only work if MID and RID header extensions are enabled/registered on media engine.
> Send side Simulcast/Track encodings

- webrtc/src/peer_connection/peer_connection_internal.rs
A minor bug in my last PR allowed an empty BUNDLE group attribute from offer to add all unmatched results into answer. The correct answer should not have any BUNDLE group either of course.
> peer_connection: sdp: Fix BUNDLE group matching

- webrtc/src/peer_connection/peer_connection_internal.rs
> peer_connection: Fix packet size for buffered simulcast packet

- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
This removes the need for some mutexes
> rtp_sender: Use a watch channel for send_called

- srtp/src/protection_profile.rs
I was looking at using the srtp code here in some code I'm playing with, but it's slightly awkward to use on its own (without the dtls code from webrtc-rs as well)--Is there any harm in making these methods public? It would make it easier to consume webrtc-rs/srtp as a standalone lib.  Specifically, I'd like to access them to write code for extracting keys from keying material.
EDIT: Making the `SessionKeys` type pub would also be useful.
> make helper methods on ProtectionProfile pub

- dtls/src/crypto/mod.rs
In a personal project I was getting errors since I made an ed25519 using openssl and it is in PKCS#8 v1 format :). This PR should fix that
> [DTLS | bugfix] allow cloning Ed2559 CryptoPrivateKeys if they have PKCS#8v1 encoding 

- media/benches/audio_buffer.rs
- rtp/benches/packet_bench.rs
- sdp/benches/bench.rs
- srtp/benches/srtp_bench.rs
- stun/benches/bench.rs
- turn/benches/bench.rs
- util/benches/bench.rs
* Cleaned up the benchmark IDs by removing the "Benchmark" prefix and using snake_case for the method names
* Split the benchmarks into groups based on the crate for easier recognition
For example, `BenchmarkLifetime/AddTo` is now `TURN/Lifetime/add_to`.
To make things easier to CTRL-F from Pion, I left the original Go-style names in comments above the benchmarks.
How the index looked before:
How it looks now:
> Make use of Criterion bench groups

- Cargo.toml
- constraints/Cargo.toml
- constraints/src/algorithms/select_settings/select_optimal.rs
- data/Cargo.toml
- dtls/Cargo.toml
- ice/Cargo.toml
- interceptor/Cargo.toml
- mdns/Cargo.toml
- media/Cargo.toml
- rtcp/Cargo.toml
- rtp/Cargo.toml
- sctp/Cargo.toml
- sdp/Cargo.toml
- srtp/Cargo.toml
- stun/Cargo.toml
- turn/Cargo.toml
- util/Cargo.toml
- webrtc/Cargo.toml
* `cfg(fuzzing)` no longer trips up `unexpected_cfgs`
* Remove the check for `feature = "total_cmp"` since the feature no longer exists
> Fix build warnings

- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
No need to store kind and transport, as they are already stored by RTPReceiverInternal.
> rtp_receiver: Get rid of fields already in internal

- webrtc/src/api/media_engine/media_engine_test.rs
- webrtc/src/api/media_engine/mod.rs
Also added a test I found in Pion, however not really a test this PR affects.
It should be said that this fix is needed for RtpReceiver to work properly when using ORTC API.
> media_engine: Properly return codec when not negotiated

- sdp/src/description/common.rs
- sdp/src/description/media.rs
- sdp/src/description/session.rs
- sdp/src/extmap/mod.rs
- sdp/src/lexer/mod.rs
- sdp/src/util/mod.rs
Hi
I noticed a large number of memory allocations during `marshal` of `SessionDescription`. And I wanna propose implementation of `fmt::Display` for `SessionDescription` struct and some fixes `fmt::Display` implementations for sub types across `sdp` crate. Also, implementation of `fmt::Display` will allow to write `SessionDescription` into preallocated strings: 
`
let mut out = String::with_capacity(1024);
write!(out, "{sdp}");
`
Performance improvement according existed benchmark:
Source `SDP/Marshal             time:   [11.610 µs 11.621 µs 11.633 µs]`
New `SDP/Marshal             time:   [4.3594 µs 4.3840 µs 4.4143 µs]`
> Reduce memory allocations for SDP marshal

- sdp/src/description/media.rs
- sdp/src/description/session.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
This allows both one-byte and two-byte headers
> sdp: Negotiate extmap-allow-mixed

- turn/Cargo.toml
Add `signal` feature for `tokio` to fix this compile error:
error[E0432]: unresolved import `tokio::signal`
--> turn/examples/turn_server_udp.rs:8:5
|
8   | use tokio::signal;
|     ^^^^^^^^^^^^^ no `signal` in the root
|
> turn: Fix examples dependencies

- interceptor/src/stream_info.rs
- webrtc/src/api/mod.rs
- webrtc/src/api/setting_engine/mod.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/peer_connection/sdp/sdp_test.rs
- webrtc/src/rtp_transceiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_codec.rs
- webrtc/src/rtp_transceiver/rtp_receiver/mod.rs
- webrtc/src/rtp_transceiver/rtp_receiver/rtp_receiver_test.rs
- webrtc/src/rtp_transceiver/rtp_sender/mod.rs
- webrtc/src/rtp_transceiver/rtp_sender/rtp_sender_test.rs
Makes `RTCRtpSender` capable of configuring RTX streams.
Incoming RTX streams are already handled at the SDP/SDES layer and then processed by `RTCRtpReceiver::receive_for_rtx`. This means interceptors can bind to remote RTX streams. This PR aims to do the same for local streams. This is related to, but not a full fix for https://github.com/webrtc-rs/webrtc/issues/295 since it doesn't implement the retransmission, but it allows the separate RTX SSRCs to be configured, negotiated, and then bound to interceptors that can do the rest.
First, a field is added to `StreamInfo` to pass information about associated streams from the SDP to the interceptor chain. This is populated for both senders and receivers. Typically the interceptor can check if the MIME type is `*/rtx` and know that the …
> Configuration of outgoing RTX streams

- dtls/src/conn/mod.rs
a context switch to a simultaneous close operation between `closed.load()` and `closed.store()` would lead to an additional unwanted close operation on the inner connection
> dtls: fix race condition in DTLSConn::close

- webrtc/src/data_channel/data_channel_parameters.rs
- webrtc/src/data_channel/data_channel_test.rs
- webrtc/src/data_channel/mod.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/sctp_transport/mod.rs
Fixes #371. Most of the change is in `RTCDataChannel::open` to match https://github.com/pion/webrtc/blob/4ef00e6e5f78647305cdd08568d16f49ae6190eb/datachannel.go#L130-L152
> webrtc: Add support for unordered unreliable data channels

- webrtc/src/track/track_local/mod.rs
- webrtc/src/track/track_local/track_local_static_rtp.rs
This makes it easier to inject Attributes to the interceptor chain just using TrackLocalStaticRTP
> track_local: Add write_rtp_with_attributes

- rtp/src/codecs/av1/av1_test.rs
- rtp/src/codecs/av1/leb128.rs
The parsing of leb128 size value a 2-pass approach rather than following the pseudocode in the AV1 spec, presumably for performance reasons. However while the maximum permitted value is indeed 32 bits, the input bytes accumulated in a `u32` are packed 7 bits per byte, thus losing relevant bits from the first byte for 5-byte values. (I believe the leb128 value can be up to 8 bytes with leading zeroes but perhaps that case was fine).
I imagine this doesn't come up where the the only large OBU in a binary presented to webrtc-rs has the size omitted, we hit this with an encoder which sets the size on every OBU.
> AV1: Correctly parse 5-byte leb128 size value

- webrtc/src/api/media_engine/mod.rs
`codec_parameters_fuzzy_search` will try to match the locally configured `apt` against the `apt` received in the offer. If the payload types differ this will not work. This change replaces the apt in the search with the original codec's payload type so they match.
This is a port of a fix in pion: https://github.com/pion/webrtc/blob/8fbf8219ddbe6b81feb24999fb547eb415e95a54/mediaengine.go#L446
> media_engine: Fix matching of apt in answer

- interceptor/src/mock/mock_stream.rs
- webrtc/src/data_channel/data_channel_test.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
This PR fixes the memory leak warning in `interceptor` and `webrtc`
1. Fix MockStream cyclic dependency to itself (interceptor)
2. Fix self reference test case in data_channel_test.rs (webrtc/data_channel)
3. Fix cyclic dependency for dtls_transport (webrtc/peer_connection)
4. Fix cyclic dependency between PeerConnectionInternal and StatsInterceptor (webrtc/peer_connection)
Related issue #133 
`RUSTFLAGS="-Z` sanitizer=leak" cargo test ` on the whole project shows no sign of memory leak.
> Bugfix/fix interceptor/webrtc unit test memory leak

- turn/src/allocation/allocation_manager.rs
- turn/src/allocation/mod.rs
The relay address is an essential part of a turn allocation, but as far as I can tell there's currently no way to get it when using `turn::server::Server`.
This may technically be a breaking change since `AllocationInfo::new` is public. Let me know if that's a problem and I can make the field an `Option` and keep the original constructor.
> turn: Add relay_addr to AllocationInfo

- .github/workflows/grcov.yml
Related to [mozilla/grcov#1240](https://github.com/mozilla/grcov/issues/1240)
I start this PR to fix the main branch's CI failure, but find out that we need to use profile-generate to replace outdated -Zprofile options.
Reference: https://doc.rust-lang.org/rustc/profile-guided-optimization.html for more information.
Reference: https://github.com/mozilla/sccache/pull/2282
> Fix grcov use profile-generate to replace outdated -Zprofile options

- media/src/io/ivf_writer/ivf_writer_test.rs
- media/src/io/ivf_writer/mod.rs
- media/src/io/ogg_writer/mod.rs
- media/src/io/ogg_writer/ogg_writer_test.rs
Fixes #634 
https://github.com/webrtc-rs/webrtc/blob/a97d49e49e694b5d6c6775b153a8d30aa41a268e/media/src/io/h264_writer/mod.rs#L52-L54
- https://github.com/pion/webrtc/pull/1995
1. Open https://jsfiddle.net/vfmcg8rk/1/
1. Copy SDP
1. cargo build --example save-to-disk-h264
1. echo $BROWSER_SDP | ./target/debug/examples/save-to-disk-h264 --video ./output.h264 --audio ./output.ogg
1. Start session 
-> `OggWriter` and `IvfWriter` works continuously
> Fix writer to skip packets with an empty payload

- ice/src/agent/mod.rs
- sctp/fuzz/fuzz_targets/packet.rs
- sctp/fuzz/fuzz_targets/param.rs
I use the library with many open/close, and I get mdns storms where the webrtc library searches for other nodes over the network in a very aggressive manner.
This has been proposed by @r-byondlabs, and might very well be the problem: if I open/close many connections, and the mdns-agents are not cleaned up, there might be many requests.
Fixes #616
> Closing mdns agent

- webrtc/src/track/track_local/mod.rs
Dear maintainers,
Thank you for your efforts in maintaining this project.
I have added two getter methods to retrieve the `mid` and `paused` fields from the `TrackLocalContext` struct.
In my project, I am implementing a custom `TrackLocal` similar to `TrackLocalStaticRTP`. The bind method provides a `TrackLocalContext`, but currently, I am unable to access all its fields because they are marked as `pub(crate)`.
https://github.com/webrtc-rs/webrtc/blob/de46a53cd6ccac2c7aee515265adce47b2a4621f/webrtc/src/track/track_local/track_local_static_rtp.rs#L177
To address this, I have introduced getter methods for the `mid` and `paused` fields, ensuring that these values can be accessed outside the crate while maintaining encapsulation.
I hope this change aligns with the project's design principles …
> Add getter methods for mid and paused in TrackLocalContext

- ice/src/agent/agent_selector.rs
- ice/src/candidate/mod.rs
A controlled agent should reply to USE-CANDIDATE binding requests, also when the candidate pair state isn't already `Succeeded`. In this case the candidate pair should be nominated immediately if the ping succeeds.
Ported from pion/ice@e0db6d2.
> ice: Fix USE-CANDIDATE in controlled agent

- srtp/src/session/mod.rs
- srtp/src/session/session_rtcp_test.rs
- srtp/src/session/session_rtp_test.rs
- webrtc/src/peer_connection/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/rtp_transceiver/mod.rs
Instead of reading first packet when probing simulcast directly from RTP stream, rather let SRTP session accept() fn return the RTP header for the first packet. This makes us able to configure interceptor and let all packets travel through the regular path.
Fixes #391
> peer_connection: Make sure all packets are read through interceptor

- examples/examples/data-channels-flow-control/data-channels-flow-control.rs
looking into #101  and it seems that there is a deadlock (tested on M1 chip) where the write_loop or read_loop randomly blocks indefinitely. The way the throughput is calculated is that it reports a degrading performance.
The actual throughput is not degrading but 0. This PR updates the code to report the throughput of every loop iteration independently.
> updating the throughput calculation in data_channel_flow_control 

- webrtc/src/data_channel/mod.rs
If we close DataChannel, read_loop may be notified and break the loop immediately without invoke on_close handler.
> Fix: Invoke onClose handler upon receiving a notification

- webrtc/src/api/media_engine/mod.rs
This is the actual mime type for HEVC/H265 defined by
https://www.iana.org/assignments/media-types/video/H265 as well as
https://datatracker.ietf.org/doc/html/rfc7798#section-7.2.1
With this change, HEVC/H265 can be negotiated for WebRTC with Safari and Chrome browsers.
Note that this might break for users who rely on the current `video/HEVC` value.
Alternatively, we could leave `MIME_TYPE_HEVC` as is (maybe with a `deprecated` flag?) and add `MIME_TYPE_H265` separately.
> Change MIME_TYPE_HEVC from video/HEVC to video/H265 (#141)

- Cargo.lock
- dtls/Cargo.toml
- dtls/examples/dial/selfsign/dial_selfsign.rs
- dtls/src/cipher_suite/cipher_suite_chacha20_poly1305_sha256.rs
- dtls/src/cipher_suite/mod.rs
- dtls/src/crypto/crypto_chacha20.rs
- dtls/src/crypto/mod.rs
This is a cipher suite supported by Chrome, and preferred on some low-end processors. I've also added an argument to the dial_selfsign example, which forces a cipher suite, and used that argument to test against the DTLS implementation in OpenSSL. Any feedback is appreciated, thank you!
Fixes #674
> Implement ChaCha20_Poly1305 cipher suite

- srtp/src/cipher/cipher_aead_aes_gcm.rs
- srtp/src/cipher/cipher_aes_cm_hmac_sha1/ctrcipher.rs
- srtp/src/cipher/cipher_aes_cm_hmac_sha1/mod.rs
- srtp/src/cipher/cipher_aes_cm_hmac_sha1/opensslcipher.rs
- srtp/src/cipher/mod.rs
- srtp/src/context/context_test.rs
- srtp/src/context/mod.rs
- srtp/src/context/srtcp_test.rs
- srtp/src/context/srtp.rs
- srtp/src/context/srtp_test.rs
- srtp/src/error.rs
- srtp/src/key_derivation.rs
- srtp/src/protection_profile.rs
- srtp/src/session/session_rtcp_test.rs
- webrtc/src/dtls_transport/mod.rs
Implements AES_256_CM_PRF as per https://datatracker.ietf.org/doc/html/rfc6188
> Make SRTP AES_256_GCM actually work

- sctp/src/association/mod.rs
Reverts webrtc-rs/webrtc#679 since it cause MacOS test deadlock and https://github.com/webrtc-rs/webrtc/issues/101 discussion mentioned still seeing the deadlock (with console_subscriber enabled)
> Revert "Fix deadlock in data-channels-flow-control example. "

- turn/src/server/mod.rs
use `command_tx.clone().ok_or(Error::ErrClosed)?` to replace `if let Some(..) { ... } else { return Err(Error::ErrClosed) }`
> turn: use ok_or() to simplify command_tx

- dtls/src/cipher_suite/cipher_suite_aes_128_ccm.rs
- dtls/src/cipher_suite/cipher_suite_aes_128_gcm_sha256.rs
- dtls/src/cipher_suite/cipher_suite_aes_256_cbc_sha.rs
- dtls/src/cipher_suite/cipher_suite_chacha20_poly1305_sha256.rs
- dtls/src/cipher_suite/cipher_suite_tls_psk_with_aes_128_gcm_sha256.rs
Replace verbose if-let-else patterns with concise ok_or() calls
for better code readability and consistency across all cipher
suite implementations.
Changes:
- CipherSuiteAes128Ccm: simplify encrypt/decrypt methods
- CipherSuiteAes128GcmSha256: simplify encrypt/decrypt methods
- CipherSuiteAes256CbcSha: simplify encrypt/decrypt methods
- CipherSuiteChaCha20Poly1305Sha256: simplify encrypt/decrypt methods
- CipherSuiteTlsPskWithAes128GcmSha256: simplify encrypt/decrypt methods
> dtls: refactor cipher suite error handling with ok_or()

- dtls/src/conn/mod.rs
Improve code readability by adding consistent spacing between async method implementations in the Conn trait for DTLSConn.
> style: add blank lines between methods in DTLSConn impl

- ice/examples/ping_pong.rs
- Replace verbose match statements with ? operator for HTTP request handling
- Fix spacing around else clauses to follow Rust formatting conventions
- Simplify error propagation in remoteAuth POST request flow
> ice/examples: improve error handling and formatting in ping_pong example

- util/src/buffer/mod.rs
Refactor the timeout error handling in `util/src/buffer/mod.rs` to use the `?` operator.
This change simplifies the code by using `map_err` to convert the timeout error to `Error::ErrTimeout`, which is more concise and idiomatic.
> util: Simplify timeout error handling in Buffer

- dtls/src/crypto/crypto_cbc.rs
This change adds more rigorous checks for the length of incoming DTLS packets when using a CBC-mode cipher.
Previously, a malformed or truncated packet could lead to out-of-bounds reads or other panics during the decryption process.
The following checks have been added:
- Ensure the total packet length is sufficient to contain at least the record layer header and one initialization vector (IV) block.
- After extracting the IV, validate that the remaining encrypted body is not empty and its length is a multiple of the cipher's block size.
These checks ensure that only structurally valid packets are processed, improving the robustness of the DTLS implementation.
> dtls: Add packet length validation in CBC decryption

- data/src/data_channel/mod.rs
- sctp/src/association/mod.rs
- sdp/src/description/session.rs
- webrtc/src/api/setting_engine/mod.rs
- webrtc/src/data_channel/data_channel_test.rs
- webrtc/src/data_channel/mod.rs
- webrtc/src/peer_connection/peer_connection_internal.rs
- webrtc/src/peer_connection/sdp/mod.rs
- webrtc/src/sctp_transport/mod.rs
Currently, webrtc-rs does not react to the `max-message-size` attribute that may be attached to an SDP.
RFC8841 introduces the `max-message-size` SDP attribute:
> The attribute can be associated with an "m=" line to indicate the maximum SCTP user message size (indicated in bytes) that an SCTP endpoint is willing to receive on the SCTP association associated with the "m=" line. Different attribute values can be used in each direction [Source](https://datatracker.ietf.org/doc/html/rfc8841#name-general-4). Browsers such as chrome typically advertise a max message size of 256KiB. Some user agents may also request a max-message-size smaller than the default 64KiB.
> Make use of the `max-message-size` SDP attribute in datachannels

- webrtc/Cargo.toml
#707 upgrades the `rand` crate to version `0.9`, however, makes use of new APIs introduced in version `0.9.1` (`rand::distr::Alphabetic`).
Specifying the version string `0.9` in `cargo.toml` allows projects that already have `rand` as a dependency to use version `0.9.0`, which leads to build failures since `rand::distr::Alphabetic` did not exist in `0.9.0` (I have experienced this myself in one of my projects).
By specifying the version `0.9.1`, we ensure that any projects that rely on this library will always pull a version of rand that has `rand::distr::Alphabetic` available.
> Require `rand` version 0.9.1 or greater, as `rand::distr::Alphabetic` does not exist in `0.9.0`, which is currently allowed

- Cargo.lock
- Cargo.toml
- data/Cargo.toml
- dtls/Cargo.toml
- ice/Cargo.toml
- interceptor/Cargo.toml
- sctp/Cargo.toml
- srtp/Cargo.toml
- stun/Cargo.toml
- turn/Cargo.toml
- util/Cargo.toml
- webrtc/Cargo.toml
[cargo-machete](https://crates.io/crates/cargo-machete) is a tool that detects unused dependencies. 
Running cargo-machete on this project yielded a number of unused dependencies that we can safely remove.
> Remove unused dependencies

- interceptor/src/report/receiver/mod.rs
- interceptor/src/report/sender/mod.rs
The current default behavior for ticker seems to be "Burst" that causes unnecessary congestion when Tokio runtime is lagging. 
Changed RR and SR ticker behavior to Skip to avoid overdue reports and catchup bursts.
> Perf: Changed RR and SR ticker behavior to Skip to avoid overdue reports and catchup bursts
